### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VoipSip** [chris-rands/emojify_python_script#7]
hello sir can i ask about something i have source code i want to protected him from thief and i will rent them for people and i want to be control at him like make him working by every ip never access with any one without make the ip access from me if try any other ip to using my code without make him access from me say can't access talk to owner

thank you i hope help me sir

**Comment by chris-rands** [comment]
I'm not sure I understand you question, but emojify is not good for securely hiding source code since it is easy to reverse the encoding. This repo it is more for education/fun
